- name: Load MongoDB schema
  when: schema_setup == "mongo"
  block:
    - name: COpy MongoDB repo file
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: Install MongoDB Client
      ansible.builtin.dnf:
        name: mongodb-mongosh
        state: latest

    - name: Load Master Data
      ansible.builtin.shell: mongosh --host mongo.{{ env }}.kranthi.online </app/db/{{ item }}.js
      loop: "{{schema_files}}"

- name: Load MySQL schema
  when: schema_setup == "mysql"
  block:
    - name: Install mysql Client
      ansible.builtin.dnf:
        name: mysql
        state: latest

    - name: Debug MySQL connection
      command: mysql -h mysql.dev.kranthi.online -u root -pRoboShop@1 -e "SHOW DATABASES;"
      register: mysql_output
      ignore_errors: yes

    - name: Print MySQL connection output
      debug:
        var: mysql_output

    - name: Load Master Data
      ansible.builtin.shell: mysql -h mysql.{{ env }}.kranthi.online -uroot -pRoboShop@1 < /app/db/{{ item }}.sql
      loop: "{{schema_files}}"

